from typing import List, Optional
from .schema import JournalRule


JOURNAL_RULES: dict[str, JournalRule] = {
    "ieee": JournalRule(
        journal_id="ieee",
        journal_name="IEEE",
        min_words=3000,
        max_words=8000,
        min_abstract_words=50,
        max_abstract_words=250,
        min_references=10,
        citation_style="ieee",
        max_figures=10,
        required_sections=["abstract", "introduction", "methodology", "results", "conclusion"],
        min_keywords=4,
        max_keywords=8,
        requires_doi=False,
        title_max_words=15,
        description="IEEE transactions and conference papers",
    ),
    "acm": JournalRule(
        journal_id="acm",
        journal_name="ACM",
        min_words=2500,
        max_words=10000,
        min_abstract_words=100,
        max_abstract_words=300,
        min_references=15,
        citation_style="acm",
        max_figures=12,
        required_sections=["abstract", "introduction", "related work", "methodology", "results", "conclusion"],
        min_keywords=3,
        max_keywords=6,
        requires_doi=False,
        title_max_words=12,
        description="ACM conference and journal papers",
    ),
    "springer": JournalRule(
        journal_id="springer",
        journal_name="Springer LNCS",
        min_words=4000,
        max_words=12000,
        min_abstract_words=50,
        max_abstract_words=200,
        min_references=20,
        citation_style="springer",
        max_figures=10,
        required_sections=["abstract", "introduction", "methodology", "experimental evaluation", "conclusion"],
        min_keywords=4,
        max_keywords=8,
        requires_doi=False,
        title_max_words=15,
        description="Springer Lecture Notes in Computer Science",
    ),
    "elsevier": JournalRule(
        journal_id="elsevier",
        journal_name="Elsevier",
        min_words=5000,
        max_words=15000,
        min_abstract_words=100,
        max_abstract_words=300,
        min_references=25,
        citation_style="elsevier",
        max_figures=8,
        required_sections=["abstract", "introduction", "materials and methods", "results", "discussion", "conclusion"],
        min_keywords=3,
        max_keywords=8,
        requires_doi=True,
        title_max_words=20,
        description="Elsevier scientific journals",
    ),
    "apa": JournalRule(
        journal_id="apa",
        journal_name="APA 7th Edition",
        min_words=2000,
        max_words=8000,
        min_abstract_words=100,
        max_abstract_words=250,
        min_references=15,
        citation_style="apa",
        max_figures=5,
        required_sections=["abstract", "introduction", "method", "results", "discussion"],
        min_keywords=3,
        max_keywords=8,
        requires_doi=False,
        title_max_words=15,
        description="APA style for social sciences",
    ),
    "mla": JournalRule(
        journal_id="mla",
        journal_name="MLA 9th Edition",
        min_words=2000,
        max_words=6000,
        min_abstract_words=0,
        max_abstract_words=0,
        min_references=5,
        citation_style="mla",
        max_figures=5,
        required_sections=["introduction", "body", "conclusion"],
        min_keywords=0,
        max_keywords=0,
        requires_doi=False,
        title_max_words=12,
        description="MLA style for humanities",
    ),
    "nature": JournalRule(
        journal_id="nature",
        journal_name="Nature",
        min_words=3000,
        max_words=6500,
        min_abstract_words=50,
        max_abstract_words=150,
        min_references=20,
        citation_style="nature",
        max_figures=6,
        required_sections=["abstract", "introduction", "results", "discussion"],
        min_keywords=3,
        max_keywords=6,
        requires_doi=False,
        title_max_words=15,
        description="Nature journal format",
    ),
    "custom": JournalRule(
        journal_id="custom",
        journal_name="Custom Format",
        min_words=None,
        max_words=None,
        min_abstract_words=None,
        max_abstract_words=None,
        min_references=None,
        citation_style="unknown",
        max_figures=None,
        required_sections=[],
        min_keywords=None,
        max_keywords=None,
        requires_doi=False,
        title_max_words=None,
        description="No predefined constraints",
    ),
}


def get_journal_rule(journal_id: str) -> Optional[JournalRule]:
    return JOURNAL_RULES.get(journal_id)


def get_all_journal_rules() -> List[JournalRule]:
    return list(JOURNAL_RULES.values())


def get_supported_journal_ids() -> List[str]:
    return list(JOURNAL_RULES.keys())
